spring:
  application:
    name: demo
  flyway:
    locations: classpath:db/migrations
    out-of-order: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:demo}}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /v3/api-docs
scalar:
  enabled: true
  path: /scalar
